// <auto-generated />
using System;
using E_Migrant.App.Persistencia.appRepositorios;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Migrant.App.Persistencia.Migrations
{
    [DbContext(typeof(appContext))]
    [Migration("20211127061609_Entidades")]
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaginaWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.Property<int>("evaluacionGerencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Entidad");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmisorId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoMensaje")
                        .HasColumnType("int");

                    b.Property<int?>("ReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Migrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacionLaboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Migrante");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiasNovedad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Novedad");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoServicio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("tipoServicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.SolicitudEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("estadoEmergencia")
                        .HasColumnType("int");

                    b.Property<int>("tipoEmergencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SolicitudEmergencia");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.SolicitudServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ComportamientoMigrante")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int>("Evaluacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAceptacionSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("estadoSolicitud")
                        .HasColumnType("int");

                    b.Property<int?>("migranteId")
                        .HasColumnType("int");

                    b.Property<int>("nivelPrioridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("migranteId");

                    b.ToTable("SolicitudServicio");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Mensaje", b =>
                {
                    b.HasOne("E_Migrant.App.Dominio.Entidades.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId");

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.Servicio", b =>
                {
                    b.HasOne("E_Migrant.App.Dominio.Entidades.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId");

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("E_Migrant.App.Dominio.Entidades.SolicitudServicio", b =>
                {
                    b.HasOne("E_Migrant.App.Dominio.Entidades.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId");

                    b.HasOne("E_Migrant.App.Dominio.Entidades.Migrante", "migrante")
                        .WithMany()
                        .HasForeignKey("migranteId");

                    b.Navigation("Entidad");

                    b.Navigation("migrante");

                    b.Navigation("Servicio");
                });
#pragma warning restore 612, 618
        }
    }
}
